// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uJcFDQxGNXArz0bYFDQy9cgynPiDbQw',
    appId: '1:572899672155:web:1c6cb2692e68dbaa527f7e',
    messagingSenderId: '572899672155',
    projectId: 'movies-5d2bf',
    authDomain: 'movies-5d2bf.firebaseapp.com',
    storageBucket: 'movies-5d2bf.firebasestorage.app',
    measurementId: 'G-ZPZP8BSL27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANpUg3UXEeYWX92Drw7gOj2vsc5hskITY',
    appId: '1:572899672155:android:8b4192f1e587fe51527f7e',
    messagingSenderId: '572899672155',
    projectId: 'movies-5d2bf',
    storageBucket: 'movies-5d2bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABz676vz6b0GSYee2oqIOjpB38Z9D4_as',
    appId: '1:572899672155:ios:a23dd29efea58793527f7e',
    messagingSenderId: '572899672155',
    projectId: 'movies-5d2bf',
    storageBucket: 'movies-5d2bf.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
